name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install packages
        run: yarn

      - name: Build packages
        run: yarn lerna run build && yarn lerna link

      - name: Run client unit tests
        run: cd packages/client && yarn test

      - name: Run util unit tests
        run: cd packages/util && yarn test

      - name: Run eth unit tests
        run: cd packages/eth && yarn test

      - name: Run react unit tests
        run: cd packages/react && yarn test
