name: Test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install packages
        run: yarn

      - name: Build packages
        run: yarn lerna run build && yarn lerna link

      - name: Run unit tests
        run: yarn lerna run test

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.PRENET_GCR_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build e2e test
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.github/docker/e2e/Dockerfile
          push: false
          outputs: type=docker
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: polybase-e2e-polybase-ts-tests

      - name: Run e2e tests
        run: |
          docker run polybase-e2e-polybase-ts-tests